version: '3.8' # We use version 3.8 syntax
services: # Here we define our service(s)
    angular-service: # The name of the service
      container_name: frontendcontainer  # Container name
      build: ./frontend # Location of our Dockerfile
      volumes: # Volume binding
        - './frontend:/usr/src/app' 
      ports: 
        - '4200:4200' # Port mapping
      command: > 
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"

    quarkus-service:
      container_name: backendcontainer
      build: 
        context: ./backend
        dockerfile: ./src/main/docker/Dockerfile.jvm
      volumes:
        - './backend:/usr/src/app'
      ports:
        - '8080:8080'
      networks:
        - backend-net  
      
networks:
  backend-net:
    driver: bridge